### ISSUE TITLE
Convert spreadsheets with large and many cell arrays

### ISSUE THREAD

**Issue by fbie** [popular-parallel-programming/funcalc-euses#3]
For now, we will ignore the folders `cs-101`, `filby`, `forms3`, `jackson` and `personal`.

1. Download sheets from http://itu.dk/people/fbie/euses-mirror/
2. Convert to XML format
3. Replace `#N/A` by `NA()`
4. Replace `=+` by `=`
5. Replace more Excel functions with their Funcalc counterparts
6. Write SDFs for missing functions

Please document, which functions you replace and which functions you implement as SDFs in the commit message.

- [x] `database/processed/2004_PUBLIC_BUGS_INVENTORY.xls`
- [x] `database/processed/Aggregate%20Governanc#A8A51.xls`
- [x] `database/processed/high_2003_belg.xls`
- [x] `financial/processed/02rise.xls`
- [x] `financial/processed/Financial-Projections.xls`
- [x] `financial/processed/financial-model-spreadsheet.xls`
- [x] `grades/processed/2002Qvols.xls`
- [x] `grades/processed/2000_places_School.xls`
- [x] `grades/processed/EducAge25.xls`
- [x] `homework/processed/notes%5CMISB200SP04H2KEY.xls`
- [x] `homework/processed/Test%20Station%20Powe#A90F3.xls`
- [x] `homework/processed/v1tmp.xls`
- [x] `inventory/processed/ny_emit99.xls`
- [x] `inventory/processed/Time.xls`
- [x] `inventory/processed/MRP_Excel.xls`
- [x] `modeling/processed/funding.xls`
- [x] `modeling/processed/modeling-3.xls`
- [x] `modeling/processed/iste-cs-2003-modeling-sim.xls`
- [x] `inventory/processed/WasteCalendarCalculat#A843B.xls`

**Comment by kirkbro** [comment]
A couple of conversion problems I have found:

- References to multi-word sheet names. I have removed whitespace from the sheet names when needed.
- Error comparison: It does not seem possible to check for specific error values in Funcalc (like `ISNA` in Excel)
- Excel supports error literals. This is fine for `#N/A -> NA()`, but for other errors like `#REF!` there is no mapping. (Excel even supports `#REF!` errors in R1C1 references - ex. `=R[-1]C/#REF!`)

**Comment by kirkbro** [comment]
[H/VLOOKUP Gist](https://gist.github.com/kirkbro/3535b80cc4a740897fe45ae78d5955f2)

**Comment by fbie** [comment]
> - Error comparison: It does not seem possible to check for specific error values in Funcalc (like ISNA in Excel)

Is it sufficient to use `ISERR` instead? Very nice Gist, by the way!

**Comment by hborum** [comment]
I am marking the sheets I am working on as done so we avoid redundant work, I will push them later when they are really done.

**Comment by fbie** [comment]
I just checked, and it seems possible to use Funcalc's `ISERROR` in lieu of `ISNA`.

**Comment by hborum** [comment]
Yes I have also used `ISERROR` as a replacement of `ISBLANK`, not entirely the same but in my sheet it has worked.
Also Excel lets reference errors turn into false values in if-statements, so I have had to rewrite.
`IF(A1, A1, 3) --> IF(NOT(ISERROR(A1)), A1, 3)` some places. 
It is more correct to do it like `IF(AND(NOT(ISERROR(A1)), A1), A1, 3)`

Here is a MATCH() that ignores the third argument and abuses positive, negative numbers to make up a tuple. https://gist.github.com/blaavogn/2dfc9996a607af7f5bef932abad50643

RIGHT(): `=EXTERN("System.String.Substring(I)T", C8, EXTERN("System.String.get_Length()I", C8)-D8)`

**Comment by hborum** [comment]
We have just finished looking through all the worksheets and they seem correct.

Some places we have had to rewrite expressions in some manner in order to get the correct result.
We are thinking of gathering our SDFs that corresponds directly to an Excel function in an example sheet.

**Comment by fbie** [comment]
> We have just finished looking through all the worksheets and they seem correct.

Great, thanks a bunch!

> We are thinking of gathering our SDFs that corresponds directly to an Excel function in an example sheet.

That sounds reasonable.

**Comment by fbie** [comment]
I have found a few more issues and re-opened the according issues #4, #5 and #6.

**Comment by hborum** [comment]
Is it possible you forgot to pull before re-opening these issues?

**Comment by fbie** [comment]
I am afraid that this is entirely possible :) However, there are still a few things left, even after I pulled. I'll update the lists accordingly.

**Comment by fbie** [comment]
There are only a few `=` comparisons on strings left.  I have added `WasteCalendarCalculat#A843B.xls` to the list as well, as it turns out that some of the spreadsheets' arrays are too small for transformation to be meaningful.  I think however that we, with this one, have sufficiently many sheets.
