### ISSUE TITLE
Fill empty but referred-to cells with zeros

### ISSUE THREAD

**Issue by fbie** [popular-parallel-programming/funcalc-euses#4]
Funcalc's blank-cell implementation is not complete. For array conversion, empty cells that are used in arithmetic expressions should be set to zero.

- [x] `database\processed\2004_PUBLIC_BUGS_INVENTORY.xml` on Inventory, columns L - N
- [x] `financial\processed\financial-model-spreadsheet.xml`
- [x] `grades\processed\2002Qvols.xml`
- [x] `homework\processed\v1tmp.xml`
- [x] `financial\processed\rise02.xml`
- [x] `financial\processed\financial-model-spreadsheet.xml`
- [x] `database\processed\Aggregate%20Governanc#A8A51.xml` on OneCountryData
- [x] `database\processed\high_2003_belg.xml` on Gross, column AR and row 132

I'll add more sheets to the list if I encounter any that have the same problem.

**Comment by kirkbro** [comment]
We cannot find any missing zeroes in `modeling\processed\funding.xml`, but there was a problem with `RATE` calls which is now fixed.

**Comment by fbie** [comment]
My mistake, I was running on the wrong branch and the cell array conversion did something weird.

**Comment by hborum** [comment]
Just to be sure, I hope we have inserted 0 and empty strings in cells that resulted in `#EMPTY` or similar.
Do you want 0 also in all cells that are referenced that does not lead to an error-value? Sort of replacing BlankCell with a NumberCell(0).

**Comment by fbie** [comment]
It would be ideal if the blank cells could be changed to contain 0. If that's impractical, we'll deal with it differently.

On Aug 3, 2017 10:11 PM, Holger Borum <notifications@github.com> wrote:

Just to be sure, I hope we have inserted 0 and empty strings in cells that resulted in #EMPTY or similar.
Do you want 0 also in all cells that are referenced that does not lead to an error-value? Sort of replacing BlankCell with a NumberCell(0).
