### ISSUE TITLE
Compare text values with EQUAL instead of =

### ISSUE THREAD

**Issue by fbie** [popular-parallel-programming/funcalc-euses#6]
The `=` operator in Funcalc is, for some reason, only defined on number values. Hence, all comparisons of text must be done by calling `EQUAL`.

- [x] `financial\processed\financial-model-spreadsheet.xml`
- [x] `inventory\processed\Time.xml` on sheet `AuditCommittee`
- [x] `financial\processed\financial-model-spreadsheet.xml`
- [x] `database\processed\Aggregate%20Governanc#A8A51.xml` on OneCountryData

**Comment by sestoft** [comment]
On 2Aug17, 10:38, "Florian Biermann" <notifications@github.com<mailto:notifications@github.com>> wrote:

The = operator in Funcalc is, for some reason, only defined on number values.

The reason has to do with efficient compilation of SDFs. This restriction could be alleviated in a number of ways, but for now use EQUAL as you suggest.

Peter
