### ISSUE TITLE
Duplicate and unused SDFs

### ISSUE THREAD

**Issue by kirkbro** [popular-parallel-programming/funcalc-euses#9]
I have created a list of SDFs in the [wiki](https://github.com/popular-parallel-programming/funcalc-euses/wiki/Sheet-defined-functions).

Creating the list it became clear that some sheets use the same functions under different names, and that some functions are not used at all.
Whenever `RATE `and `PMT `are used the entire `@tvm` and `@Goalseek ` sheets are included.

Is it worth while to trim unused SDFs and reuse the same SDFs between sheets where possible?

**Comment by fbie** [comment]
> Is it worth while to trim unused SDFs and reuse the same SDFs between sheets where possible?

No, if the functions are not called their overhead is marginal.
